### ISSUE TITLE
Multiline text can be incorrectly recognised as elm code

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#16]
I have found a 'false-positive' identification of elm code when elm-like text is embedded in a multiline string:

```elm
falsePositive : String
falsePositive =
    """Some multiline text that looks a bit like some elm code
thisIsNotAFunction : Int
thisIsNotAFunction =
    99
"""
```

It happens because text inside multiline quotes can (correctly) start a line.

While this is an unlikely scenario, it may help in refining the regexp used to identify type annotations.

**Comment by kachkaev** [comment]
Very good point, I did not think about it! Do we only echo the first symbol in the block? If so, the UX should not suffer despite a definite bug in [literate-elm / codeInsights.ts](https://github.com/gicentre/litvis/blob/master/packages/literate-elm/src/codeInsights.ts).

The trouble is that covering cases like this will probably require a proper tokenisation of a program rather than simply applying a regexp to each row. Of course we can skip rows between `"""`, but what if there is an escaped `"""` etc. within a string or another edge case. Let's gather more examples of edge cases here, add them to [tests](https://github.com/gicentre/litvis/blob/master/packages/literate-elm/src/codeInsights.findIntroducedSymbols.test.ts) and see how far we can go with a 'hacky' regexp approach.

**Comment by kachkaev** [comment]
The implementation in 083a592 is using regexps and so is somewhat naive, but I hope it will cover most of the real-world cases. If someone still manages to trigger a false-positive inside a multi-line string, we can reopen this issue or create a new one. I'd try using regexps here as much as we can since this is much cheaper than tokenising the code.
