### ISSUE TITLE
Easy way to flush the literate-elm cache

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#24]
Users of litvis sometimes need to flush the `literate-elm` cache if previously compiled code blocks have become corrupted or if dependencies have been updated. Currently to do this they have to remove the folder inside the hidden .mume folder:  `~/.mume/literate-elm`.

If they have hidden folders hidden in the file view of their operating system this is a little tricky for beginners. The instructions for doing so will depend on operating system, where the home directory is located, and whether hidden files are shown or not.

It would be more beginner-friendly if a _flush the litvis cache_ option was available directly from within Atom and VS Code (probably via keyboard shortcut and editor menu option).

**Comment by kachkaev** [comment]
Clearing cache will be possible via the command palette in the next release.

**Atom**  
<img width="530" alt="Screenshot 2019-03-17 at 19 27 50" src="https://user-images.githubusercontent.com/608862/54497009-7d691b00-48ed-11e9-899f-59c287da57eb.png">

**VSCode**  
<img width="614" alt="Screenshot 2019-03-17 at 19 46 29" src="https://user-images.githubusercontent.com/608862/54497010-84902900-48ed-11e9-8d9e-bb640368b7d7.png">

**Comment by kachkaev** [comment]
One caveat to be aware of in Atom: the new command is only available after the package has been 'activated'. For MPE, this happens when a markdown source code is opened (no preview necessary). Atom packages have a somewhat odd concept of activators, which should help optimize memory and CPU.

https://github.com/gicentre/markdown-preview-enhanced-with-litvis/blob/86e73636acb64f27a33577b4b2737437693abf22/package.json#L11-L19

I tried adding the new command to the list of `activationCommands`, but it did not work. For some reason I don't quite understand, running the command for the first time warms up the package, but does not delete the files.
