### ISSUE TITLE
Interactive mode no longer shows tooltips by default. Is this desired behaviour?

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#35]
Since the update to litvis 0.18.0, the default behaviour of rendered visualizations is now not to show tooltips. Previously, simply making a code block interactive showed a tooltip for all fields that were rendered with some kind of mark. Tooltips are rendered if they are set explicitly. For example:

````
```elm {v interactive}
barChart : Spec
barChart =
    let
        data =
            dataFromColumns []
                << dataColumn "a" (strs [ "A", "B", "C", "D", "E", "F", "G" ])
                << dataColumn "b" (nums [ 28, 55, 43, 91, 81, 53, 19 ])

        enc =
            encoding
                << position X [ pName "a", pMType Ordinal ]
                << position Y [ pName "b", pMType Quantitative ]
                << tooltips
                    [ [ tName "a", tMType Ordinal ]
                    , [ tName "b", tMType Quantitative ]
                    ]
    in
    toVegaLite [ data [], bar [], enc [] ]
```
````

The question is whether a specification without explicit tooltips should show them in interactive mode.

### Arguments against the new default and attempting to revert to pre- 0.18.0 behaviour:

- This is technically a breaking change as default behaviour is now different for a spec in interactive mode without explicit tooltip setting.
- Having tooltips now requires more code in the spec than it did previously

### Arguments for the new behaviour:

- Consistent with default behaviour of Vega-lite javascript and the official Vega-lite editor (no tooltips by default)
- Easier to enable other interaction without tooltips (previously to do this we had to set an empty tooltips list).
- Specification is semantically more correct (no tooltips unless we specify them).

I think on balance I prefer the new no-tooltips-by-default behaviour but would be interested in others' views. Perhaps one solution might be the ability to switch between the two behaviours, perhaps with a `tooltips` / `t` option in the code block header.

**Comment by kachkaev** [comment]
I investigated why the default behaviour has changed and found https://github.com/vega/vega-lite/pull/4919. So it seems that the only way to enable tooltips in vega-lite specs is to change the JSON:

```diff
- "mark": "bar",
+ "mark": { "type": "bar", "tooltip": true },
```

Vega-embed still has a `tooltip` option, which I can inject on this line:
https://github.com/gicentre/mume-with-litvis/blob/7d3ed4fbe5924a5634a96e9cd4abc3bc1d780a70/src/markdown-engine.ts#L628

However, it does not seem to work if I just go for `tooltip: true` without changing the vega-lite spec. The only thing I could control so far is theming of a a tooltip, which is already being shown via the spec. 

```js
vegaEmbed(vegaEl, spec, { actions: false, renderer: 'svg', tooltip: { theme: 'dark' })
```
↓
<img width="200" alt="Screenshot 2019-10-02 at 09 20 55" src="https://user-images.githubusercontent.com/608862/66028918-08aaa680-e4f6-11e9-94aa-fac72befe5a2.png">

Because of the breaking change vega-lite v4, I don't see how we could turn `tooltips` / `t` attribute into a tooltip. So far it seems to me that requiring tooltip definition in the spec is the only option going forward.

**Comment by jwoLondon** [comment]
Thanks for investigating Alex. I should have remembered the change in vegalite.

Given this is an intended change from Vega/Vega-lite, I don't think we need change anything here (and as above, I think the new default behaviour is preferable anyway).

For info, when using `elm-vegalite` one can turn on tooltips to reproduce the old behaviour (assuming the code block is `interactive`) with `maTooltop ttEncoding` (see [ttEncoding](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#ttEncoding)). For example,

```elm
barChart : Spec
barChart =
    let
        data =
            dataFromColumns []
                << dataColumn "a" (strs [ "A", "B", "C" ])
                << dataColumn "b" (nums [ 28, 55, 43 ])

        enc =
            encoding
                << position X [ pName "a", pMType Ordinal ]
                << position Y [ pName "b", pMType Quantitative ]
    in
    toVegaLite [ data [], enc [], bar [ maTooltip ttEncoding ] ]
```
There is also a [ttNone](https://package.elm-lang.org/packages/gicentre/elm-vegalite/latest/VegaLite#ttNone) option for disabling tooltips explicitly. I will change the documentation for both these functions in elm-vegalite to indicate the default is now equivalent to `ttNone` rather than `ttEncoding`.

No changes required in litvis, so I will close this issue.
