### ISSUE TITLE
Markdown linter uses 2 space indentations for list items but default is 1

### ISSUE THREAD

**Issue by jwoLondon** [gicentre/litvis#48]
Markdown [linting rule MD030](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md030), which determines the number of spaces after a list marker, suggests 1 space by default. Validation of markdown on our GitHub setup suggests 2 and so generates listing warnings with a default formatted document. 

`MD030/list-marker-space Spaces after list markers [Expected: 2; Actual: 1]`

Is there any reason why we shouldn't use the default of 1?

**Comment by kachkaev** [comment]
Hi Jo!

We use one space for unordered lists, so that blocks in list items were padded by two spaces.

````markdown
- Hello

  Two leading spaces here.
  
  ```
  code listing
  ```

- World
````

If we do the same for the ordered lists, these elements (including code listings) will be padded by three spaces.

````markdown
1. Hello

   Three leading spaces here.
  
   ```
   code listing
   ```

1. World
````

Adding one extra space makes this offset even, which simplifies actions like select + tab / select + shift tab in the editor.

````markdown
1.  Hello

    Four leading spaces here.
  
    ```
    code listing
    ```

1.  World
```

Because we don't know in advance which lists will have blocks and which ones will remain simple, the same rule applies everywhere. Happy to update our setup if there is possibility for some other convenient configuration.

**Comment by jwoLondon** [comment]
Ah, OK, that makes sense. I will update my local markdown linting config to conform with this.
